"""empty message

Revision ID: f2f2acb1b5ce
Revises: 
Create Date: 2020-12-08 23:51:32.234621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f2acb1b5ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Suppliers')
    op.drop_table('Shippers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shippers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Shippers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Shippers_pkey')
    )
    op.create_table('Suppliers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Suppliers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address1', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('address2', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('postalcode', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('fax', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=75), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_methods', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type_goods', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('discount_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_supplier_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('size_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('logo', sa.VARCHAR(length=75), autoincrement=False, nullable=True),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Suppliers_pkey')
    )
    # ### end Alembic commands ###
