# These Constants are for Auth0 environment variables,
# as well as for any secret keys

DATABASE_URL = 'DATABASE_URL'
AUTH0_DOMAIN = 'AUTH0_DOMAIN'
ALGORITHMS = ' ALGORITHMS'
AUTH0_API_AUDIENCE = 'AUTH0_API_AUDIENCE'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_CLIENT_ID = 'AUTH0_CLIENT_ID'
AUTH0_CLIENT_SECRET = 'AUTH0_CLIENT_SECRET'
JWT_PAYLOAD = 'JWT_PAYLOAD'
PROFILE_KEY = 'PROFILE_KEY'
SECRET_KEY = 'SECRET_KEY'
