--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Categories; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public."Categories" (
    id integer NOT NULL,
    category_name character varying(60) NOT NULL,
    description character varying(255) NOT NULL,
    picture character varying(50),
    active boolean NOT NULL
);


ALTER TABLE public."Categories" OWNER TO "THEJAGSTER";

--
-- Name: Categories_id_seq; Type: SEQUENCE; Schema: public; Owner: THEJAGSTER
--

CREATE SEQUENCE public."Categories_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Categories_id_seq" OWNER TO "THEJAGSTER";

--
-- Name: Categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: THEJAGSTER
--

ALTER SEQUENCE public."Categories_id_seq" OWNED BY public."Categories".id;


--
-- Name: Customers; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public."Customers" (
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    address1 character varying(60) NOT NULL,
    address2 character varying(60),
    city character varying(30) NOT NULL,
    state character varying(30) NOT NULL,
    postalcode character varying(15) NOT NULL,
    country character varying(50) NOT NULL,
    phone character varying(25),
    email character varying(75),
    creditcard integer,
    creditcard_type_id integer,
    card_exp_month character varying(15),
    card_exp_year integer,
    billing_address character varying(60),
    billing_city character varying(30),
    billing_region character varying(60),
    billing_country character varying(60),
    billing_postalcode character varying(15),
    shipping_address character varying(60),
    shipping_city character varying(30),
    shipping_region character varying(60),
    shipping_country character varying(60),
    shipping_postalcode character varying(15),
    date_entered timestamp without time zone
);


ALTER TABLE public."Customers" OWNER TO "THEJAGSTER";

--
-- Name: Customers_id_seq; Type: SEQUENCE; Schema: public; Owner: THEJAGSTER
--

CREATE SEQUENCE public."Customers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Customers_id_seq" OWNER TO "THEJAGSTER";

--
-- Name: Customers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: THEJAGSTER
--

ALTER SEQUENCE public."Customers_id_seq" OWNED BY public."Customers".id;


--
-- Name: Order_Details; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public."Order_Details" (
    id integer NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    discount double precision NOT NULL,
    total double precision NOT NULL,
    fulfilled boolean NOT NULL,
    bill_date timestamp without time zone NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public."Order_Details" OWNER TO "THEJAGSTER";

--
-- Name: Order_Details_id_seq; Type: SEQUENCE; Schema: public; Owner: THEJAGSTER
--

CREATE SEQUENCE public."Order_Details_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Order_Details_id_seq" OWNER TO "THEJAGSTER";

--
-- Name: Order_Details_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: THEJAGSTER
--

ALTER SEQUENCE public."Order_Details_id_seq" OWNED BY public."Order_Details".id;


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public."Orders" (
    id integer NOT NULL,
    order_date timestamp without time zone NOT NULL,
    sales_tax double precision NOT NULL,
    "timestamp" double precision NOT NULL,
    transact_status character varying(50) NOT NULL,
    paid boolean NOT NULL,
    payment_date timestamp without time zone NOT NULL,
    fulfilled boolean NOT NULL,
    payment_id integer NOT NULL,
    customer_id integer NOT NULL
);


ALTER TABLE public."Orders" OWNER TO "THEJAGSTER";

--
-- Name: Orders_id_seq; Type: SEQUENCE; Schema: public; Owner: THEJAGSTER
--

CREATE SEQUENCE public."Orders_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Orders_id_seq" OWNER TO "THEJAGSTER";

--
-- Name: Orders_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: THEJAGSTER
--

ALTER SEQUENCE public."Orders_id_seq" OWNED BY public."Orders".id;


--
-- Name: Payment; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public."Payment" (
    id integer NOT NULL,
    payment_type character varying(60) NOT NULL,
    allowed boolean NOT NULL
);


ALTER TABLE public."Payment" OWNER TO "THEJAGSTER";

--
-- Name: Payment_id_seq; Type: SEQUENCE; Schema: public; Owner: THEJAGSTER
--

CREATE SEQUENCE public."Payment_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Payment_id_seq" OWNER TO "THEJAGSTER";

--
-- Name: Payment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: THEJAGSTER
--

ALTER SEQUENCE public."Payment_id_seq" OWNED BY public."Payment".id;


--
-- Name: Products; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public."Products" (
    id integer NOT NULL,
    product_name character varying(60) NOT NULL,
    product_description character varying(255) NOT NULL,
    msrp double precision NOT NULL,
    picture character varying(50),
    category_id integer[] NOT NULL
);


ALTER TABLE public."Products" OWNER TO "THEJAGSTER";

--
-- Name: Products_id_seq; Type: SEQUENCE; Schema: public; Owner: THEJAGSTER
--

CREATE SEQUENCE public."Products_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Products_id_seq" OWNER TO "THEJAGSTER";

--
-- Name: Products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: THEJAGSTER
--

ALTER SEQUENCE public."Products_id_seq" OWNED BY public."Products".id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: THEJAGSTER
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO "THEJAGSTER";

--
-- Name: Categories id; Type: DEFAULT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Categories" ALTER COLUMN id SET DEFAULT nextval('public."Categories_id_seq"'::regclass);


--
-- Name: Customers id; Type: DEFAULT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Customers" ALTER COLUMN id SET DEFAULT nextval('public."Customers_id_seq"'::regclass);


--
-- Name: Order_Details id; Type: DEFAULT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Order_Details" ALTER COLUMN id SET DEFAULT nextval('public."Order_Details_id_seq"'::regclass);


--
-- Name: Orders id; Type: DEFAULT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Orders" ALTER COLUMN id SET DEFAULT nextval('public."Orders_id_seq"'::regclass);


--
-- Name: Payment id; Type: DEFAULT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Payment" ALTER COLUMN id SET DEFAULT nextval('public."Payment_id_seq"'::regclass);


--
-- Name: Products id; Type: DEFAULT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Products" ALTER COLUMN id SET DEFAULT nextval('public."Products_id_seq"'::regclass);


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public."Categories" (id, category_name, description, picture, active) FROM stdin;
1	Mens-Apparel	This category is for mens apparel	static/images/categories/mens_apparel	t
2	Womens-Apparel	This category is for womens apparel	static/images/categories/womens_apparel	t
3	Holiday	This category is for holiday items	static/images/categories/holiday	t
4	Misc	This category is for miscellaneous items	static/images/categories/misc	t
\.


--
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public."Customers" (id, first_name, last_name, address1, address2, city, state, postalcode, country, phone, email, creditcard, creditcard_type_id, card_exp_month, card_exp_year, billing_address, billing_city, billing_region, billing_country, billing_postalcode, shipping_address, shipping_city, shipping_region, shipping_country, shipping_postalcode, date_entered) FROM stdin;
\.


--
-- Data for Name: Order_Details; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public."Order_Details" (id, price, quantity, discount, total, fulfilled, bill_date, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public."Orders" (id, order_date, sales_tax, "timestamp", transact_status, paid, payment_date, fulfilled, payment_id, customer_id) FROM stdin;
\.


--
-- Data for Name: Payment; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public."Payment" (id, payment_type, allowed) FROM stdin;
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public."Products" (id, product_name, product_description, msrp, picture, category_id) FROM stdin;
1	Mens Summer Blue Tee	This is a tapered mens summer blue t-shirt.	25	static/images/products/1	{1}
2	Womens Sweater	This is a white wool womens sweater	40	static/images/products/2	{2}
3	Mens Holiday Sweater	This is a husky red mens holiday sweater.	40	static/images/products/3	{1,3}
4	Holiday Unisex Socks	This is a pair of black holiday unisex socks.	12	static/images/products/4	{1,2,3,4}
5	Womens Watch	This is a womens watch in gold.	120	static/images/products/5	{2,4}
\.


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: THEJAGSTER
--

COPY public.alembic_version (version_num) FROM stdin;
\.


--
-- Name: Categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: THEJAGSTER
--

SELECT pg_catalog.setval('public."Categories_id_seq"', 4, true);


--
-- Name: Customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: THEJAGSTER
--

SELECT pg_catalog.setval('public."Customers_id_seq"', 1, false);


--
-- Name: Order_Details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: THEJAGSTER
--

SELECT pg_catalog.setval('public."Order_Details_id_seq"', 1, false);


--
-- Name: Orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: THEJAGSTER
--

SELECT pg_catalog.setval('public."Orders_id_seq"', 1, false);


--
-- Name: Payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: THEJAGSTER
--

SELECT pg_catalog.setval('public."Payment_id_seq"', 1, false);


--
-- Name: Products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: THEJAGSTER
--

SELECT pg_catalog.setval('public."Products_id_seq"', 5, true);


--
-- Name: Categories Categories_category_name_key; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "Categories_category_name_key" UNIQUE (category_name);


--
-- Name: Categories Categories_pkey; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "Categories_pkey" PRIMARY KEY (id);


--
-- Name: Customers Customers_pkey; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "Customers_pkey" PRIMARY KEY (id);


--
-- Name: Order_Details Order_Details_pkey; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Order_Details"
    ADD CONSTRAINT "Order_Details_pkey" PRIMARY KEY (id);


--
-- Name: Orders Orders_pkey; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_pkey" PRIMARY KEY (id);


--
-- Name: Payment Payment_pkey; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Payment"
    ADD CONSTRAINT "Payment_pkey" PRIMARY KEY (id);


--
-- Name: Products Products_pkey; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "Products_pkey" PRIMARY KEY (id);


--
-- Name: Products Products_product_name_key; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "Products_product_name_key" UNIQUE (product_name);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: Order_Details Order_Details_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Order_Details"
    ADD CONSTRAINT "Order_Details_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public."Orders"(id);


--
-- Name: Order_Details Order_Details_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Order_Details"
    ADD CONSTRAINT "Order_Details_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public."Products"(id);


--
-- Name: Orders Orders_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public."Customers"(id);


--
-- Name: Orders Orders_payment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: THEJAGSTER
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_payment_id_fkey" FOREIGN KEY (payment_id) REFERENCES public."Payment"(id);


--
-- PostgreSQL database dump complete
--

